version: "3"
services:
  backend:
    image: samyukth8/backend-login
    ports:
      - "3000:3000"

  frontend:
    image: samyukth8/frontend-login
    ports:
      - "8080:80"
    depends_on:
      - backend
